// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1478oFY6I2W_bsUFLCDZ_5pX2eF-5eyk',
    appId: '1:873508229902:web:874f8162c970af4356bd5f',
    messagingSenderId: '873508229902',
    projectId: 'defecttracker-41bba',
    authDomain: 'defecttracker-41bba.firebaseapp.com',
    storageBucket: 'defecttracker-41bba.firebasestorage.app',
    measurementId: 'G-0C8RY3N0X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEsY7nYzzP7_CqwfjipbMmdw-ifXW4EdY',
    appId: '1:873508229902:android:63aa16075dea42eb56bd5f',
    messagingSenderId: '873508229902',
    projectId: 'defecttracker-41bba',
    storageBucket: 'defecttracker-41bba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsRhE67WAQmGhJy14M2djB-U5BD6MmgXY',
    appId: '1:873508229902:ios:9f584bd0eddfea2d56bd5f',
    messagingSenderId: '873508229902',
    projectId: 'defecttracker-41bba',
    storageBucket: 'defecttracker-41bba.firebasestorage.app',
    iosBundleId: 'com.example.defectTrackerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsRhE67WAQmGhJy14M2djB-U5BD6MmgXY',
    appId: '1:873508229902:ios:9f584bd0eddfea2d56bd5f',
    messagingSenderId: '873508229902',
    projectId: 'defecttracker-41bba',
    storageBucket: 'defecttracker-41bba.firebasestorage.app',
    iosBundleId: 'com.example.defectTrackerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1478oFY6I2W_bsUFLCDZ_5pX2eF-5eyk',
    appId: '1:873508229902:web:06a103f0f4e197f456bd5f',
    messagingSenderId: '873508229902',
    projectId: 'defecttracker-41bba',
    authDomain: 'defecttracker-41bba.firebaseapp.com',
    storageBucket: 'defecttracker-41bba.firebasestorage.app',
    measurementId: 'G-XD88FSXZJ1',
  );
}
